version: '3.6'

services:  
  elasticsearch:
    image: elasticsearch:6.8.2
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - node.name=node-1
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - node.master=true
      - node.data=true
      - http.port=9200
      - transport.tcp.port=9300
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - MAX_LOCKED_MEMORY=unlimited
    ulimits:
      memlock:
        soft: -1
        hard: -1
